version: 2

updates:
- package-ecosystem: "pip-compile"
  directory: "/requirements"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  allow:
  - dependency-type: all
  rebase-strategy: "disabled"
  ignore:
  # Always ignore elasticsearch, future versions are always incompatible with our provider
  - dependency-name: "elasticsearch"
  # These update basically every day, and 99.9% of the time we don't care
  - dependency-name: "boto3"
  - dependency-name: "boto3-stubs"
  - dependency-name: "botocore"
  - dependency-name: "botocore-stubs"
  groups:
    python-package:
      # Keep rest of package together
      patterns:
        - "*"
    celery:
      # Keep both celery and kombu together
      patterns:
        - "celery"
        - "kombu"
    psycopg:
      # Keep both psycopg and psycopg-c together
      patterns:
        - "psycopg*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: "daily"
