version: 2

updates:
  - package-ecosystem: pip
    directory: /requirements/
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    allow:
      - dependency-type: all
    rebase-strategy: "disabled"
    groups:
      requirements:
        # Keep rest of package together
        patterns: ["*"]
      #   exclude-patterns: ["celery", "kombu", "psycopg*"]
      # celery:
      #   # Keep both celery and kombu together
      #   patterns: ["celery", "kombu"]
      # psycopg:
      #   # Keep both psycopg and psycopg-c together
      #   patterns: ["psycopg*"]
    ignore:
      # Always ignore elasticsearch, future versions are always incompatible with our provider
      - dependency-name: "elasticsearch"
      # These update basically every day, and 99.9% of the time we don't care
      - dependency-name: "boto3"
      - dependency-name: "boto3-stubs"
      - dependency-name: "botocore"
      - dependency-name: "botocore-stubs"
  
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
